set more off
ssc install unique, all
ssc install winsor2, all
ssc install reghdfe, all
ssc install ivreg2, all
ssc install ftools, all
ssc install regsave, all
ssc install texsave, all
ssc install estout, all
ssc install ivreghdfe, all
ssc install ranktest, all
ssc install kountry, all
ssc install mipolate, all
ssc install tabout, all
ssc install numdate, all
ssc install binscatter, all
ssc install egenmore, all
ssc install coefplot, all
ssc install grstyle, all
ssc install erepost, all
ssc install tolong, all
ssc install labutil, all
ssc install lincomest, all
ssc install durbinh, all
ssc install wbopendata, all
ssc install seq, all
ssc install outreg2, all
ssc install outreg, all
ssc install epctile, all
ssc install xtscc, all
ssc install tuples, all
ssc install cdfplot, all
ssc install distinct, all
ssc install parmest, all
